import test from 'node:test';
import assert from 'node:assert/strict';
// CSS-free policy is imported from the dedicated policy boundary.
import {mobilePlayPolicy} from '../src/online/mobile-play-policy.js';
const PLAY_PHASES=['countdown','playing','roundOver','matchOver'];
const PHASES=['lobby',...PLAY_PHASES];
test('a joined phone is the same landscape controller in every play phase (#13)',()=>{for(const phase of PLAY_PHASES){const state={joined:true,phase,displayOnly:false};assert.deepEqual(mobilePlayPolicy(state,true,390,844),{phone:true,lobby:false,active:true,blocked:true},phase);assert.deepEqual(mobilePlayPolicy(state,true,844,390),{phone:true,lobby:false,active:true,blocked:false},phase);assert.deepEqual(mobilePlayPolicy(state,true,320,568),{phone:true,lobby:false,active:true,blocked:true},phase);}});
// #134: the lobby is a phone screen in either orientation — no controller, no rotate gate — for a joined rider and for a host who has not taken a seat yet.
test('a phone in the lobby gets the lobby screen, never the controller',()=>{for(const joined of [true,false])for(const [width,height] of [[390,844],[844,390],[320,568]])assert.deepEqual(mobilePlayPolicy({joined,phase:'lobby',displayOnly:false},true,width,height),{phone:true,lobby:true,active:false,blocked:false},`joined=${joined} ${width}x${height}`);});
test('unjoined, display-only, desktop and mouse views keep the normal layout',()=>{for(const phase of PHASES){const state={joined:true,phase,displayOnly:false};assert.equal(mobilePlayPolicy({...state,joined:false},true,390,844).active,false,phase);assert.deepEqual(mobilePlayPolicy({...state,displayOnly:true},true,390,844),{phone:false,lobby:false,active:false,blocked:false},phase);assert.equal(mobilePlayPolicy(state,false,390,844).phone,false,phase);assert.equal(mobilePlayPolicy(state,true,1366,1024).phone,false,phase);assert.equal(mobilePlayPolicy(state,true,701,1200).phone,false,phase);}});
// #44: a terminal room close leaves the controller so the header status ("Room ended — return to menu to start again") and MENU are reachable without ☰ MENU.
test('an ended room is not joined play on any phone size or phase',()=>{for(const phase of PHASES){const ended={joined:true,phase,displayOnly:false,ended:true};for(const [width,height] of [[390,844],[844,390],[320,568]])assert.deepEqual(mobilePlayPolicy(ended,true,width,height),{phone:false,lobby:false,active:false,blocked:false},`${phase} ${width}x${height}`);assert.equal(mobilePlayPolicy({...ended,ended:false,phase:'playing'},true,844,390).active,true,phase);}});
