import test from 'node:test';
import assert from 'node:assert/strict';
import {HostSession,type RoomCommand} from '../src/online/host-session.js';
import {defaultRoomSettings} from '../src/shared/room-settings.js';
type Input=Extract<RoomCommand,{type:'input'}>;
function fixture(){const s=new HostSession('host',{...defaultRoomSettings(),weights:{}},{token:()=> 'first-shot'});s.command('host',{type:'join',name:'Host'});s.command('guest',{type:'join',name:'Guest'});let seq=0;const command=(bomb:boolean,bombAction?:Input['bombAction']):Input=>({type:'input',scope:s.controlScope('host')!,intendedTick:s.game.tick+1,seq:seq++,left:false,right:false,bomb,...(bombAction?{bombAction}:{})});const start=()=>{s.command('host',{type:'action',action:'start'});while(s.game.phase==='countdown')s.advance();};start();return{s,command,start,player:()=>s.game.players.get('host')!};}
function fire(f:ReturnType<typeof fixture>){assert.equal(f.s.command('host',f.command(true,'press')),undefined);f.s.advance();assert.notEqual(f.player().bombChargeStartedTick,undefined,'fresh press must begin charge without preliminary neutral');f.s.command('host',f.command(false,'release'));f.s.advance();assert.equal([...f.s.game.bombs.values()].filter(b=>b.ownerId==='host').length,1);}
test('first fresh press after countdown and explicit lobby reset fires without a neutral packet',()=>{const f=fixture();fire(f);f.s.command('host',{type:'action',action:'lobby'});f.start();fire(f);});
test('idle watchdog without a held gesture does not block the first fresh shot',()=>{const f=fixture();f.s.command('host',f.command(false));f.s.advance();for(let i=0;i<12;i++)f.s.advance();assert.ok(f.player().alive);fire(f);});
test('new scope rejects old held/release packets but accepts a fresh press',()=>{const f=fixture();const oldPress=f.command(true,'press'),oldRelease=f.command(false,'release');f.s.command('host',oldPress);f.s.advance();f.s.clear();assert.match(f.s.command('host',oldRelease)!,/scope expired/);assert.match(f.s.command('host',oldPress)!,/scope expired/);fire(f);});
test('watchdog still suppresses interrupted held gestures until an actual release',()=>{const f=fixture();f.s.command('host',f.command(false));f.s.advance();f.s.command('host',f.command(true,'press'));f.s.advance();assert.notEqual(f.player().bombChargeStartedTick,undefined);for(let i=0;i<10;i++)f.s.advance();assert.equal(f.player().bombChargeStartedTick,undefined);f.s.command('host',f.command(true));f.s.advance();f.s.command('host',f.command(false,'release'));f.s.advance();assert.equal(f.s.game.bombs.size,0);fire(f);});
