import type { RuntimeText } from "./game.js";

/** Neutral wording for a new game; Fuse Riders supplies its own (`games/fuse-riders/src/online/fuse-game.ts`). */
export const defaultText: RuntimeText = {
  solo: "Solo · you and the AI",
  connected: "Connected · direct game link",
  preparing: "Connected · preparing the room",
  waitingForGame: "Connected · waiting for the game",
  waitingFor: "Waiting for {name}",
  lagging: "Connected · {name} lagging",
  waitingForDisplay: "Waiting for a display",
  recovering: "Recovering the room from {who} — {peer}",
  recoverFromOne: "a player",
  recoverFromAll: "the players",
  waitingForHost: "Waiting for the game — {peer}",
  loading: "Waiting for the game to load",
  hostOnly: "Only the host can manage the room",
  invalidSettings: "Invalid settings",
  matchRunning: "A match is already running",
  needTwo: "Two players are needed to start",
  rematchLater: "Rematch is available after the match ends",
  full: "Room is full",
  fullWithBots: "Room is full (AI included)",
  botNotFound: "AI player not found",
  botBetweenRounds: "Remove AI between rounds or return to menu",
  stillLoading: "The room is still loading",
  chooseName: "Choose a name",
  reconnectFirst: "Reconnect before joining",
  stopWatching: "Stop watching before taking a seat",
  leaveSeat: "Leave your seat before watching",
  watchersFull: "Room is full (spectators)",
  hostReplaced: "This host tab was replaced — use the newer tab",
  couldNotLoad: "Could not load the game — reload this page",
  outOfSync: "Simulation out of sync — reload this page",
  resyncing: "Simulation corrected · resyncing",
  mismatch: {
    stale: "This page is out of date — reload this page",
    staleRider: "A player is on an older game version — they must reload",
    staleRoom:
      "This room is on an older game version — start a new room, or have its players reload",
    unknown: "A player is on a different game version — reload this page",
    replyToStale: "This room runs a newer game version — reload this page",
    replyToNewer: "This room is on an older game version — start a new room",
    replyToUnknown:
      "This room runs a different game version — reload this page",
  },
};
