import assert from 'node:assert/strict';
import {chromium,webkit,type Page} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
interface Metrics {tick:number;sentBytes:number;frameP95:number;replication:{mode:string;acceptedBatches:number;hashMismatches:number;replicaTick:number|null;fullViewPeers:number;controllerPeers:number;binarySentBytes:number}}
const metrics=(page:Page)=>page.evaluate(()=>JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics!)) as Promise<Metrics>;
const browsers=[await chromium.launch({headless:true}),await webkit.launch({headless:true})];const pages:Page[]=[];const errors:string[]=[];const samples:unknown[]=[];
const make=async(engine:number,mobile=false)=>{const context=await browsers[engine]!.newContext({viewport:mobile?{width:844,height:390}:{width:1200,height:850},...(mobile?{isMobile:true,hasTouch:true}:{})});const page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));pages.push(page);return page;};
try{
 console.log('Opening isolated room');const host=await make(0);
 // Application-delivery impairment, not an OS/UDP network simulation. Bound outstanding delayed packets.
 await host.addInitScript(()=>{type Payload=string|Blob|ArrayBuffer|ArrayBufferView<ArrayBuffer>;const original=RTCDataChannel.prototype.send as (this:RTCDataChannel,data:Payload)=>void;let count=0,pending=0;const lab=window as unknown as {actionImpair:boolean};lab.actionImpair=false;RTCDataChannel.prototype.send=function(data:Payload){if(!lab.actionImpair||!(data instanceof ArrayBuffer||ArrayBuffer.isView(data)))return original.call(this,data);count++;if(count%7===0||pending>=64)return;const channel=this;const serial=count;const copy=data instanceof ArrayBuffer?data.slice(0):new Uint8Array(data.buffer,data.byteOffset,data.byteLength).slice();pending++;setTimeout(()=>{pending--;if(channel.readyState==='open'){original.call(channel,copy);if(serial%5===0)original.call(channel,copy);}},count%3===0?350:100);};});
 await host.goto((process.env.ONLINE_URL??'http://localhost:8812/')+'?replication=actions&renderer=canvas');await host.getByRole('button',{name:'CREATE ROOM',exact:true}).click();await host.waitForURL(/room=/);
 const url=new URL(host.url());assert.equal(url.searchParams.get('replication'),'actions');url.searchParams.set('renderer','canvas');await host.goto(url.href);
 await host.getByPlaceholder('Your name').fill('Host');await host.getByRole('button',{name:'JOIN AS PLAYER',exact:true}).click();
 for(let i=1;i<5;i++){const guest=await make(i%2,true);if(i===1)await guest.addInitScript(()=>{const original=RTCDataChannel.prototype.send as (this:RTCDataChannel,data:string|Blob|ArrayBuffer|ArrayBufferView<ArrayBuffer>)=>void;let sent=false;RTCDataChannel.prototype.send=function(data:string|Blob|ArrayBuffer|ArrayBufferView<ArrayBuffer>){if(!sent&&typeof data==='string'){const v=JSON.parse(data);if(v.data?.type==='actionHello'){v.data={type:'actionUnsupported'};data=JSON.stringify(v);sent=true;}}return original.call(this,data);};});await guest.goto(url.href);await guest.getByPlaceholder('Your name').fill(`Rider ${i}`);await guest.getByRole('button',{name:'JOIN AS PLAYER',exact:true}).click();await host.locator(':is(.online-roster,.room-riders):visible').getByText(`Rider ${i}`,{exact:false}).waitFor();}
 console.log('Five riders admitted');await host.getByRole('button',{name:'INVITE / TV',exact:true}).click();const href=await host.getByRole('link',{name:'OPEN TV VIEW',exact:true}).getAttribute('href');assert.ok(href);const tvUrl=new URL(href,url);assert.equal(tvUrl.searchParams.get('replication'),'actions');tvUrl.searchParams.set('renderer','canvas');await host.getByRole('button',{name:'CLOSE',exact:true}).click();const tv=await make(1);await tv.goto(tvUrl.href);
 await host.waitForFunction(()=>{const m=JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}');return m.replication?.fullViewPeers===5;});
 for(const page of pages.slice(1))await page.waitForFunction(()=>{const m=JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}');return m.replication?.acceptedBatches>10;});
 for(const fault of ['silent','wrong-rules'] as const){
   const bad=await make(0);await bad.addInitScript(mode=>{const original=RTCDataChannel.prototype.send as (this:RTCDataChannel,data:string|Blob|ArrayBuffer|ArrayBufferView<ArrayBuffer>)=>void;RTCDataChannel.prototype.send=function(data:string|Blob|ArrayBuffer|ArrayBufferView<ArrayBuffer>){if(typeof data==='string'){const v=JSON.parse(data);if(v.data?.type==='actionHello'){if(mode==='silent')return;v.data.rules='incompatible-rules';data=JSON.stringify(v);}}return original.call(this,data);};},fault);
   await bad.goto(url.href);await bad.waitForFunction(expected=>document.querySelector('.online-header')?.textContent?.includes(expected),fault==='silent'?'handshake timed out':'protocol unavailable');assert.equal((await metrics(bad)).replication.replicaTick,null);await bad.context().close();pages.pop();
 }
 console.log('Negotiation failures and wrong-sender rejection verified');
 await host.getByRole('button',{name:'START RACE',exact:true}).click();
 const sample=async(label:string)=>{const values=await Promise.all(pages.map(metrics));for(const m of values)assert.equal(m.replication.hashMismatches,0);samples.push({label,at:Date.now(),values});};
 console.log('All full replicas advancing');await sample('joined');
 for(let i=0;i<3;i++){await host.waitForTimeout(5000);await sample('normal');}
 await host.evaluate(()=>{(window as unknown as {actionImpair:boolean}).actionImpair=true;});
 for(let i=0;i<9;i++){await host.waitForTimeout(5000);await sample('delayed-dropped-duplicated-reordered');}
 await host.evaluate(()=>{(window as unknown as {actionImpair:boolean}).actionImpair=false;});
 console.log('Impaired delivery complete');await pages[1]!.reload();await pages[1]!.waitForFunction(()=>{const m=JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}');return m.replication?.acceptedBatches>10;});await sample('guest-reconnect');
 await host.keyboard.press('Escape');await host.getByRole('button',{name:'MAIN MENU',exact:true}).click();await host.getByRole('button',{name:'ROOM SETTINGS',exact:true}).click();await host.getByRole('radio',{name:'Shared TV + phone controls',exact:true}).check();await host.getByRole('button',{name:'SAVE SETTINGS',exact:true}).click();
 await host.waitForFunction(()=>{const r=JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}').replication;return r?.controllerPeers===4&&r?.fullViewPeers===1;});
 for(const guest of pages.slice(1,5))await guest.waitForFunction(()=>JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}').replication?.replicaTick===null);
 await host.getByRole('button',{name:'START RACE',exact:true}).click();for(let i=0;i<3;i++){await host.waitForTimeout(5000);await sample('shared-tv-lightweight-controllers');}
 await host.keyboard.press('Escape');await host.getByRole('button',{name:'MAIN MENU',exact:true}).click();await host.getByRole('button',{name:'ROOM SETTINGS',exact:true}).click();await host.getByRole('radio',{name:'Full game on each device',exact:true}).check();await host.getByRole('button',{name:'SAVE SETTINGS',exact:true}).click();
 for(const guest of pages.slice(1,5))await guest.waitForFunction(()=>JSON.parse(document.querySelector<HTMLElement>('#app')!.dataset.metrics??'{}').replication?.replicaTick!==null);
 console.log('Role transitions complete');await sample('full-view-restored');assert.deepEqual(errors,[]);console.log('Action room acceptance passed: mixed engines, five riders plus TV, delivery impairment, guest reconnect and role transitions.');
}catch(error){console.error(error);for(const [i,page] of pages.entries())console.log('PAGE',i,await page.evaluate(()=>({dialogs:[...document.querySelectorAll('dialog[open]')].map(x=>x.textContent),buttons:[...document.querySelectorAll('button')].filter(x=>x.getBoundingClientRect().width>0).map(x=>x.textContent),status:document.querySelector('.online-status')?.textContent})).catch(()=>null));throw error;}finally{
 await mkdir('artifacts',{recursive:true});await writeFile('artifacts/action-room-browser.json',JSON.stringify({revision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).length>0,method:'Local legacy Worker signalling, real reliable WebRTC channels, desktop Chromium host, mixed Chromium/WebKit guests and WebKit TV, Canvas renderer. Simulated application packet delay100/350ms, every7th binary send dropped, duplicate sends, max64 delayed. Not physical phones or WAN/UDP evidence.',samples,errors},null,2)+'\n');
 for(const page of pages)if(!page.isClosed())console.log('FINAL',await page.evaluate(()=>document.querySelector('.online-status')?.textContent??'').catch(()=>''),await metrics(page).catch(()=>null));
 await Promise.all(browsers.map(b=>b.close()));
}
