steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile.cloud
      - --build-arg=BUILD_REVISION=${_REVISION}
      - --tag=${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
