import {chromium,webkit} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.HOME_URL??'http://127.0.0.1:4188/';const results:object[]=[];await mkdir('artifacts',{recursive:true});
for(const [name,type] of [['chrome',chromium],['webkit',webkit]] as const){const browser=await type.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();page.setDefaultTimeout(15000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.stack??e.message));
 try{await page.goto(new URL('?solo=1',base).href);await page.locator('.mobile-rotate-gate').waitFor({state:'visible'});await page.locator('.mobile-tools-toggle').click();await page.screenshot({path:`artifacts/mobile-portrait-tools-${name}.png`});await page.getByRole('button',{name:'MAIN MENU',exact:true}).click();await page.getByRole('button',{name:'START RACE',exact:true}).click();await page.locator('.mobile-rotate-gate').waitFor({state:'visible'});
 await page.setViewportSize({width:844,height:390});await page.locator('.mobile-rotate-gate').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer?.startsWith('phaser-'));
 const bounds=await page.locator('.online-controls button').evaluateAll(buttons=>buttons.map(b=>{const r=b.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};}));for(const [i,r] of bounds.entries()){assert.ok(Math.abs(r.x-i*844/3)<1);assert.ok(Math.abs(r.width-844/3)<1);assert.equal(r.y,0);assert.equal(r.height,390);}
 const fit=await page.locator('.online-arena').evaluate(canvas=>getComputedStyle(canvas).objectFit);assert.equal(fit,'contain');await page.waitForTimeout(3100);assert.equal(await page.locator('.mobile-control-hints').evaluate(e=>Number(getComputedStyle(e).opacity)),0);
 await page.screenshot({path:`artifacts/mobile-landscape-faded-${name}.png`});await page.mouse.move(100,200);await page.mouse.down();assert.ok(await page.locator('.online-controls button').first().evaluate(e=>e.classList.contains('active')));await page.setViewportSize({width:390,height:844});await page.locator('.mobile-rotate-gate').waitFor({state:'visible'});assert.equal(await page.locator('.online-controls button.active').count(),0);await page.mouse.up();
 await page.locator('.mobile-tools-toggle').click();await page.getByRole('button',{name:'HEAD',exact:true}).click();await page.getByRole('button',{name:'CLOSE',exact:true}).click();await page.locator('.mobile-tools-toggle').click();await page.getByRole('button',{name:'MAIN MENU',exact:true}).click();assert.equal(await page.locator('.mobile-tools-toggle').isVisible(),false);
 assert.deepEqual(errors,[]);results.push({browser:name,passed:true,portraitGate:true,thirds:bounds,objectFit:fit,hintsFaded:true,rotationCancelledHeldInput:true,portraitMenuAccessible:true,errors});console.log(`PASS ${name} mobile landscape`);
 }catch(error){results.push({browser:name,passed:false,error:String(error),errors});throw error;}finally{await browser.close();await writeFile('artifacts/mobile-landscape-smoke.json',JSON.stringify(results,null,2));}
}
