import {chromium,webkit,type Page} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.ONLINE_URL??'http://127.0.0.1:8796/';await mkdir('artifacts',{recursive:true});const results:object[]=[];
async function qr(page:Page){await page.locator('.shared-lobby').waitFor({state:'visible'});await page.waitForFunction(()=>{const image=document.querySelector<HTMLImageElement>('.shared-lobby img');return image?.complete&&image.naturalWidth>0;});}
for(const [name,type] of [['chrome',chromium],['webkit',webkit]] as const){const browser=await type.launch({headless:true});const errors:string[]=[];let guestSockets=0;
 try{const hc=await browser.newContext({viewport:{width:1280,height:800}}),gc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),dc=await browser.newContext({viewport:{width:1280,height:800}});const host=await hc.newPage(),guest=await gc.newPage(),display=await dc.newPage();for(const page of [host,guest,display]){page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push(e.stack??e.message));}guest.on('websocket',()=>guestSockets++);
 await host.goto(base);await host.getByLabel('Where will you play?').selectOption('shared');await host.getByRole('button',{name:'CREATE ROOM',exact:true}).click();await host.waitForURL(/room=/);const invite=host.url(),code=new URL(invite).searchParams.get('room')!;assert.match(code,/^[A-Z]{2}[0-9]{2}$/);await qr(host);assert.equal(await host.locator('.shared-room-code').textContent(),code);assert.equal(await host.locator('.online-arena').isVisible(),false);
 await guest.addInitScript(()=>{Reflect.set(window,'__sharedStates',[]);window.addEventListener('fuse-benchmark',event=>{const detail=(event as CustomEvent).detail;if(detail.kind==='snapshot'){const states=Reflect.get(window,'__sharedStates') as unknown[];states.push(detail);if(states.length>200)states.shift();}});});
 await guest.goto(invite+'&benchmark=1');await guest.getByPlaceholder('Your name').fill('QR guest');await guest.getByRole('button',{name:'JOIN AS PLAYER',exact:true}).click();await host.locator('.online-roster').getByText('QR guest',{exact:false}).waitFor();await guest.locator('.online-controls').waitFor({state:'visible'});assert.equal(await guest.locator('.shared-lobby').isVisible(),false);
 const controlBounds=[];for(const viewport of [{width:320,height:568},{width:390,height:844},{width:844,height:390}]){await guest.setViewportSize(viewport);await guest.locator('.controller-only').waitFor();const bounds=await guest.locator('.online-controls button').evaluateAll(buttons=>buttons.map(b=>{const r=b.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};}));for(const [i,r] of bounds.entries()){assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=viewport.width+1&&r.y+r.height<=viewport.height+1,'control must fit viewport');assert.ok(r.height>=viewport.height*(viewport.width>viewport.height?.45:.20),'control must be thumb-sized');assert.ok(r.width>=viewport.width*(viewport.width>viewport.height?.25:i===1?.8:.4),'control width must be useful');}controlBounds.push({viewport,bounds});await guest.screenshot({path:`artifacts/shared-controller-${name}-${viewport.width}.png`});}
 await display.goto(invite+'&display=1');await qr(display);assert.equal(await display.locator('.shared-room-code').textContent(),code);await host.getByRole('button',{name:'ADD AI',exact:true}).click();await host.getByRole('button',{name:/Remove AI/}).waitFor();await host.screenshot({path:`artifacts/shared-qr-${name}.png`});
 await host.getByRole('button',{name:'START RACE',exact:true}).click();await display.locator('.shared-lobby').waitFor({state:'hidden'});await display.locator('.online-arena').waitFor({state:'visible'});await display.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer?.startsWith('phaser-'));await guest.waitForFunction(()=>{const states=Reflect.get(window,'__sharedStates') as {phase:string}[];return states.at(-1)?.phase==='playing';});const beforeAngle=await guest.evaluate(()=>{const states=Reflect.get(window,'__sharedStates') as {playerId:string;players:{id:string;angle:number}[]}[];const state=states.at(-1)!;return state.players.find(p=>p.id===state.playerId)!.angle;});const left=guest.getByRole('button',{name:'◀',exact:true}),leftBounds=await left.boundingBox();assert.ok(leftBounds);await guest.mouse.move(leftBounds.x+leftBounds.width/2,leftBounds.y+leftBounds.height/2);await guest.mouse.down();try{await guest.waitForFunction(before=>{const states=Reflect.get(window,'__sharedStates') as {playerId:string;players:{id:string;angle:number}[];motionResults?:{status:string}[]}[];const state=states.at(-1)!;const player=state.players.find(p=>p.id===state.playerId)!;const change=Math.atan2(Math.sin(player.angle-before),Math.cos(player.angle-before));return change<-.01&&state.motionResults?.some(r=>r.status==='applied');},beforeAngle);assert.ok(await left.evaluate(e=>e.classList.contains('active')),'held input feedback');await new Promise(resolve=>setTimeout(resolve,500));assert.equal(await guest.evaluate(()=>getSelection()?.toString()??''),'');assert.equal(await left.evaluate(e=>e.dispatchEvent(new Event('contextmenu',{bubbles:true,cancelable:true}))),false,'control context menu prevented');assert.equal(await left.evaluate(e=>e.dispatchEvent(new Event('selectstart',{bubbles:true,cancelable:true}))),false,'control selection prevented');}finally{await guest.mouse.up();}await guest.waitForFunction(()=>!document.querySelector('.online-controls button')?.classList.contains('active'));
 await host.getByRole('button',{name:'MAIN MENU',exact:true}).click();await qr(host);await qr(display);
 await host.getByRole('button',{name:'MENU',exact:true}).click();await host.getByRole('button',{name:'END ROOM',exact:true}).click();await host.getByRole('link',{name:/PLAY SOLO/}).waitFor();await guest.getByText(/room.*(ended|expired)/i).first().waitFor();const socketCount=guestSockets;await new Promise(resolve=>setTimeout(resolve,1800));assert.equal(guestSockets,socketCount,'ended room must not auto-rejoin');assert.deepEqual(errors,[]);results.push({browser:name,passed:true,shortCodePattern:true,hostQr:true,tvQr:true,startReset:true,endedWithoutReconnect:true,controlBounds,inputApplied:true});console.log(`PASS ${name} shared QR/end room`);
 }catch(error){results.push({browser:name,passed:false,error:String(error),errors});throw error;}
 finally{await browser.close();await writeFile('artifacts/shared-room-smoke.json',JSON.stringify(results,null,2));}
}
