import {chromium,webkit,type Page} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import { smokeTimeout } from './smoke-timeout.js';
const base=process.env.ONLINE_URL??'http://127.0.0.1:8796/';await mkdir('artifacts',{recursive:true});const results:object[]=[];
async function qr(page:Page){await page.locator('.shared-lobby').waitFor({state:'visible'});await page.waitForFunction(()=>{const image=document.querySelector<HTMLImageElement>('.shared-lobby img');return image?.complete&&image.naturalWidth>0;});}
for(const [name,type] of [['chrome',chromium],['webkit',webkit]] as const){const browser=await type.launch({headless:true});const errors:string[]=[];let guestSockets=0;let diagnosticPages:Record<string,Page>={};
 try{const hc=await browser.newContext({viewport:{width:1280,height:800},...(name==='chrome'?{permissions:['clipboard-read','clipboard-write']}:{})}),gc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),dc=await browser.newContext({viewport:{width:1280,height:800}});const host=await hc.newPage(),guest=await gc.newPage(),display=await dc.newPage();diagnosticPages={host,guest,display};for(const page of [host,guest,display]){page.setDefaultTimeout(smokeTimeout(25000));page.on('pageerror',e=>errors.push(e.stack??e.message));}guest.on('websocket',()=>guestSockets++);
 await host.goto(base);await host.getByRole('radio',{name:'Shared TV',exact:true}).check();await host.getByRole('button',{name:'CREATE ROOM',exact:true}).click();await host.waitForURL(/room=/);const invite=host.url(),code=new URL(invite).searchParams.get('room')!;assert.match(code,/^[A-Z]{2}[0-9]{2}$/);await qr(host);assert.equal(await host.locator('.shared-room-code').textContent(),code);assert.equal(await host.locator('.online-arena').isVisible(),false);
 // The lobby hands out the join link as text next to the QR, and COPY reports what it managed to do (the clipboard is unavailable on some headless browsers).
 const joinUrl=(await host.locator('.room-qr-url').textContent())!;assert.equal(joinUrl,invite,`lobby link must be the invite: ${joinUrl}`);
 const qrCardBox=(await host.locator('.room-qr-card').boundingBox())!,linkBox=(await host.locator('.room-qr-link').boundingBox())!;
 assert.ok(linkBox.x>=qrCardBox.x-1&&linkBox.x+linkBox.width<=qrCardBox.x+qrCardBox.width+1&&linkBox.y+linkBox.height<=qrCardBox.y+qrCardBox.height+1,`link must sit inside the QR card: ${JSON.stringify({qrCardBox,linkBox})}`);
 await host.getByRole('button',{name:'COPY',exact:true}).click();await host.waitForFunction(()=>document.querySelector('.room-qr-copy')?.textContent!=='COPY');
 const copyLabel=(await host.locator('.room-qr-copy').textContent())!;assert.match(copyLabel,/^(COPIED|COPY FAILED)$/);
 // Only Chromium grants a readable clipboard here, and a blocked read can hang, so the check is bounded and skipped elsewhere.
 const clipboard=name==='chrome'&&copyLabel==='COPIED'?await Promise.race([host.evaluate(()=>navigator.clipboard.readText()).catch(()=>'unreadable'),new Promise<string>(resolve=>setTimeout(()=>resolve('unreadable'),4000))]):'skipped';
 if(clipboard!=='skipped'&&clipboard!=='unreadable')assert.equal(clipboard,invite,'COPIED must mean the link is on the clipboard');
 await host.waitForFunction(()=>document.querySelector('.room-qr-copy')?.textContent==='COPY');
 await guest.addInitScript(()=>{Reflect.set(window,'__sharedStates',[]);window.addEventListener('fuse-benchmark',event=>{const detail=(event as CustomEvent).detail;if(detail.kind==='snapshot'){const states=Reflect.get(window,'__sharedStates') as unknown[];states.push(detail);if(states.length>200)states.shift();}});});
 await guest.goto(invite+'&benchmark=1');await guest.getByPlaceholder('Your name').fill('QR guest');await guest.getByRole('button',{name:'JOIN AS PLAYER',exact:true}).click();await host.locator('.room-riders').getByText('QR guest',{exact:true}).waitFor();await guest.locator('.phone-lobby .shared-lobby').waitFor({state:'visible'});assert.equal(await guest.locator('.online-controls').isVisible(),false,'no thirds in the lobby');
 // #134: a joined phone in the lobby is a lobby screen in every viewport and orientation — its rider row on screen, one menu, no rotate gate, no thirds. The thirds are checked once the race starts.
 const controlBounds=[];for(const viewport of [{width:320,height:568},{width:390,height:844},{width:844,height:390}]){await guest.setViewportSize(viewport);await guest.locator('.phone-lobby').waitFor();assert.equal(await guest.locator('.mobile-play').count(),0,'the lobby is not the controller');assert.equal(await guest.locator('.mobile-rotate-gate').isVisible(),false,'no rotate gate in the lobby');const me=guest.locator('.room-riders').getByText('QR guest',{exact:true});await me.scrollIntoViewIfNeeded();const rider=(await me.boundingBox())!;assert.ok(rider.x>=0&&rider.y>=0&&rider.x+rider.width<=viewport.width+1&&rider.y+rider.height<=viewport.height+1,`rider row must be on screen: ${JSON.stringify(rider)}`);assert.equal(await guest.locator('button:visible').filter({hasText:/MENU/}).count(),1,'one menu button in the lobby');assert.match((await guest.locator('.online-notice').textContent())??'',/^Waiting for the host/,'guest sees why it waits');controlBounds.push({viewport,rider});await guest.screenshot({path:`artifacts/shared-lobby-${name}-${viewport.width}.png`});}
 // TV VIEW replaced the invite dialog: it opens the display role straight away.
 const [tvTab]=await Promise.all([hc.waitForEvent('page'),host.getByRole('button',{name:'TV VIEW',exact:true}).click()]);await tvTab.waitForLoadState('domcontentloaded');assert.match(tvTab.url(),new RegExp(`room=${code}&display=1`));assert.equal(await host.locator('dialog[open]').count(),0,'TV VIEW must not open a dialog');await tvTab.close();
 await display.goto(invite+'&display=1');await qr(display);assert.equal(await display.locator('.shared-room-code').textContent(),code);await host.getByRole('button',{name:'ADD AI',exact:true}).click();await host.getByRole('button',{name:/Remove AI/}).waitFor();await host.screenshot({path:`artifacts/shared-qr-${name}.png`});
 await host.getByRole('button',{name:'START RACE',exact:true}).click();await display.locator('.shared-lobby').waitFor({state:'hidden'});await display.locator('.online-arena').waitFor({state:'visible'});await display.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer?.startsWith('phaser-'));await guest.waitForFunction(()=>{const states=Reflect.get(window,'__sharedStates') as {phase:string}[];return states.at(-1)?.phase==='playing';});await guest.locator('.mobile-play').waitFor();const fullThirds=await guest.locator('.online-controls button').evaluateAll(buttons=>buttons.map(b=>{const r=b.getBoundingClientRect();return{x:r.x,width:r.width,height:r.height};}));for(const [i,r] of fullThirds.entries()){assert.ok(Math.abs(r.x-i*844/3)<1);assert.ok(Math.abs(r.width-844/3)<1);assert.equal(r.height,390);}assert.equal(await guest.locator('.online-arena').isVisible(),false);assert.equal(await guest.locator('.mobile-control-hints').evaluate(e=>getComputedStyle(e).animationName),'none');await guest.screenshot({path:`artifacts/shared-landscape-thirds-${name}.png`});const beforeAngle=await guest.evaluate(()=>{const states=Reflect.get(window,'__sharedStates') as {playerId:string;players:{id:string;angle:number}[]}[];const state=states.at(-1)!;return state.players.find(p=>p.id===state.playerId)!.angle;});const left=guest.getByRole('button',{name:'◀',exact:true}),leftBounds=await left.boundingBox();assert.ok(leftBounds);await guest.mouse.move(leftBounds.x+leftBounds.width/2,leftBounds.y+leftBounds.height/2);await guest.mouse.down();try{await guest.waitForFunction(before=>{const states=Reflect.get(window,'__sharedStates') as {playerId:string;players:{id:string;angle:number}[]}[];const state=states.at(-1)!;const player=state.players.find(p=>p.id===state.playerId)!;const change=Math.atan2(Math.sin(player.angle-before),Math.cos(player.angle-before));return change<-.01;},beforeAngle);assert.ok(await left.evaluate(e=>e.classList.contains('active')),'held input feedback');await new Promise(resolve=>setTimeout(resolve,500));assert.equal(await guest.evaluate(()=>getSelection()?.toString()??''),'');assert.equal(await left.evaluate(e=>e.dispatchEvent(new Event('contextmenu',{bubbles:true,cancelable:true}))),false,'control context menu prevented');assert.equal(await left.evaluate(e=>e.dispatchEvent(new Event('selectstart',{bubbles:true,cancelable:true}))),false,'control selection prevented');}finally{await guest.mouse.up();}await guest.waitForFunction(()=>!document.querySelector('.online-controls button')?.classList.contains('active'));
 await host.getByRole('button',{name:'MAIN MENU',exact:true}).click();await qr(host);await qr(display);
 await host.getByRole('button',{name:'MENU',exact:true}).click();await host.getByRole('button',{name:'END ROOM',exact:true}).click();await host.getByRole('link',{name:/PLAY SOLO/}).waitFor(); // #44: a joined phone must see the ended room without opening ☰ MENU — the thirds controller gives way to the ordinary header, status and MENU.
 const ended=guest.getByText(/room.*(ended|expired)/i).first();await ended.waitFor({state:'visible'});const endedBox=await ended.boundingBox();
 assert.ok(endedBox&&endedBox.width>0&&endedBox.height>0&&endedBox.x>=0&&endedBox.y>=0&&endedBox.x+endedBox.width<=844&&endedBox.y+endedBox.height<=390,`ended text must be visible inside the phone viewport: ${JSON.stringify(endedBox)}`);
 assert.equal(await guest.locator('.mobile-play').count(),0,'ended room must leave the phone thirds controller');
 assert.equal(await guest.locator('.online-controls').isVisible(),false,'ended room must not keep live-looking controls');
 await guest.getByRole('button',{name:'MENU',exact:true}).waitFor({state:'visible'});await guest.screenshot({path:`artifacts/shared-ended-phone-${name}.png`});
 const socketCount=guestSockets;await new Promise(resolve=>setTimeout(resolve,1800));assert.equal(guestSockets,socketCount,'ended room must not auto-rejoin');assert.deepEqual(errors,[]);results.push({browser:name,passed:true,shortCodePattern:true,hostQr:true,tvQr:true,joinLink:joinUrl,copyLabel,clipboard,startReset:true,endedWithoutReconnect:true,endedVisibleOnPhone:endedBox,controlBounds,inputApplied:true});console.log(`PASS ${name} shared QR/end room`);
 }catch(error){console.error(`shared room smoke failed (${name}):`,String(error));
  // Every page's own status and link diagnostics (the MENU text), so a failure says which leg stalled (#132). Each read is
  // bounded: evaluate ignores the page timeout, and a stuck renderer must not hang the job and hide the error above.
  const pages:Record<string,object>={};for(const [role,page] of Object.entries(diagnosticPages)){pages[role]=await Promise.race([page.evaluate(()=>({status:document.querySelector('.online-status')?.textContent??null,link:document.querySelector<HTMLElement>('#app')?.dataset.linkDiagnostics??null,body:document.body.innerText.slice(0,800)})).catch(e=>({unavailable:String(e)})),new Promise<object>(resolve=>setTimeout(()=>resolve({unavailable:'page did not answer within 4 s'}),4000))]);await page.screenshot({path:`artifacts/shared-failure-${name}-${role}.png`,timeout:5000}).catch(()=>{});}
  console.error(`shared room diagnostics (${name}):`,JSON.stringify(pages,null,2));results.push({browser:name,passed:false,error:String(error),errors,pages});throw error;}
 finally{await browser.close();await writeFile('artifacts/shared-room-smoke.json',JSON.stringify(results,null,2));}
}
