import {chromium,webkit,type Page} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.ONLINE_URL??'http://127.0.0.1:8796/';await mkdir('artifacts',{recursive:true});const results:object[]=[];
async function qr(page:Page){await page.locator('.shared-lobby').waitFor({state:'visible'});await page.waitForFunction(()=>{const image=document.querySelector<HTMLImageElement>('.shared-lobby img');return image?.complete&&image.naturalWidth>0;});}
for(const [name,type] of [['chrome',chromium],['webkit',webkit]] as const){const browser=await type.launch({headless:true});const errors:string[]=[];let guestSockets=0;
 try{const hc=await browser.newContext({viewport:{width:1280,height:800}}),gc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),dc=await browser.newContext({viewport:{width:1280,height:800}});const host=await hc.newPage(),guest=await gc.newPage(),display=await dc.newPage();for(const page of [host,guest,display]){page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push(e.stack??e.message));}guest.on('websocket',()=>guestSockets++);
 await host.goto(base);await host.getByLabel('Where will you play?').selectOption('shared');await host.getByRole('button',{name:'CREATE ROOM',exact:true}).click();await host.waitForURL(/room=/);const invite=host.url(),code=new URL(invite).searchParams.get('room')!;assert.match(code,/^[A-Z]{2}[0-9]{2}$/);await qr(host);assert.equal(await host.locator('.shared-room-code').textContent(),code);assert.equal(await host.locator('.online-arena').isVisible(),false);
 await guest.goto(invite);await guest.getByPlaceholder('Your name').fill('QR guest');await guest.getByRole('button',{name:'JOIN AS PLAYER',exact:true}).click();await host.locator('.online-roster').getByText('QR guest',{exact:false}).waitFor();await guest.locator('.online-controls').waitFor({state:'visible'});assert.equal(await guest.locator('.shared-lobby').isVisible(),false);
 await display.goto(invite+'&display=1');await qr(display);assert.equal(await display.locator('.shared-room-code').textContent(),code);await host.getByRole('button',{name:'ADD AI',exact:true}).click();await host.getByRole('button',{name:/Remove AI/}).waitFor();await host.screenshot({path:`artifacts/shared-qr-${name}.png`});
 await host.getByRole('button',{name:'START RACE',exact:true}).click();await display.locator('.shared-lobby').waitFor({state:'hidden'});await display.locator('.online-arena').waitFor({state:'visible'});await display.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer?.startsWith('phaser-'));await host.getByRole('button',{name:'MAIN MENU',exact:true}).click();await qr(host);await qr(display);
 await host.getByRole('button',{name:'MENU',exact:true}).click();await host.getByRole('button',{name:'END ROOM',exact:true}).click();await host.getByRole('link',{name:/PLAY SOLO/}).waitFor();await guest.getByText(/room.*(ended|expired)/i).first().waitFor();const socketCount=guestSockets;await new Promise(resolve=>setTimeout(resolve,1800));assert.equal(guestSockets,socketCount,'ended room must not auto-rejoin');assert.deepEqual(errors,[]);results.push({browser:name,passed:true,shortCodePattern:true,hostQr:true,tvQr:true,startReset:true,endedWithoutReconnect:true});console.log(`PASS ${name} shared QR/end room`);
 }catch(error){results.push({browser:name,passed:false,error:String(error),errors});throw error;}
 finally{await browser.close();await writeFile('artifacts/shared-room-smoke.json',JSON.stringify(results,null,2));}
}
